name: "ProxyRack"
slug: "proxyrack"
description: "Share your connection with ProxyRack POP"
version: "latest"
init: false
legacy: true
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
image: jonnx/proxyrack-pop
options:
  UUID: ""
  API_KEY: ""
  DEVICE_NAME: "HomeAssistant"
schema:
  UUID: str
  API_KEY: str
  DEVICE_NAME: str
