name: "ProxyRack"
slug: "proxyrack"
description: "Share your connection with ProxyRack POP"
version: "latest"
init: false
legacy: true
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
image: detfisch/proxyrack-pop
options:
  UUID: ""
  API_KEY: ""
  DEVICE_NAME: "HomeAssistant"
  PR_SCRIPT_URL: ""
schema:
  UUID: str
  API_KEY: str
  DEVICE_NAME: str
  PR_SCRIPT_URL: str
