name: "Bitping"
slug: "bitping"
description: "Earn money with your spare internet"
version: "25.4.8-1"
init: false
legacy: true
image: bitping/bitpingd
arch:
  - amd64
  - aarch64
  - armv7
options:
  BITPING_EMAIL: ""
  BITPING_PASSWORD: ""
  BITPING_MFA: ""
schema:
  BITPING_EMAIL: str
  BITPING_PASSWORD: str
  BITPING_MFA: str?
map:
  - type: addon_config
    read_only: false
    path: /root/.bitpingd
