name: "Traffmonetizer"
slug: "traffmonetizer"
description: "Share your internet connection and make money online"
version: "1.0"
init: false
legacy: true
arch:
  - amd64
  - aarch64
  - armv7
options:
  token: ""
  device-name: ""
schema:
  token: str
  device-name: str
