name: "Pawns.app"
slug: "pawns"
description: "Extra Income Made Easy"
version: "0.33.2"
init: false
legacy: true
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
options:
  email: ""
  password: ""
  device: "HomeAssistant"
  deviceId: "homeassistant"
schema:
  email: str
  password: str
  device: str
  deviceId: str
